### ISSUE TITLE
Incorrect Battery Type

### ISSUE THREAD

**Issue by blacklopo** [rosswarren/epevermodbus#12]
BUG report:
----
Battery Parameters:
Rated charging current: 40A
Rated load current: 40A
Battery real rated voltage: 24V
Traceback (most recent call last):
  File "/home/kali/.local/bin/epevermodbus", line 8, in <module>
    sys.exit(main())
  File "/home/kali/.local/lib/python3.10/site-packages/epevermodbus/command_line.py", line 60, in main
    print(f"Battery type: {controller.get_battery_type()}")
  File "/home/kali/.local/lib/python3.10/site-packages/epevermodbus/driver.py", line 271, in get_battery_type
    return {0: "USER_DEFINED", 1: "SEALED", 2: "GEL", 3: "FLOODED"}[
KeyError: 0.02
---

In file driver.py, line 272 should be:
            self.retriable_read_register(0x9000, 0, 3)
instead of 
            self.retriable_read_register(0x9000, 2, 3)

regards
Pavel

**Comment by rosswarren** [comment]
Thanks for reporting, this should be fixed by https://github.com/rosswarren/epevermodbus/pull/13
