### ISSUE TITLE
more of a question.....

### ISSUE THREAD

**Issue by jimlynnjulian** [rosswarren/epevermodbus#30]
I have a Triron 4210N and LiTime 12V/100Ah battery. I goot settings from the manufacturer and substituted them in your example script. This worked okay except for an error. 
This is not about the error.
I wanted to append the boost and equalization duration parameters to your script. A syntax error occurred after I added what seemd, from the driver.py file, to be the correct protocol.

    battery_voltage_control_registers = {
        'over_voltage_disconnect_voltage': 15.0,
        'charging_limit_voltage': 14.6,
        'over_voltage_reconnect_voltage': 13.6,
        'equalize_charging_voltage': 14.0,
        'boost_charging_voltage': 14.3,
        'float_charging_voltage': 13.8,
        'boost_reconnect_charging_voltage': 13.3,
        'low_voltage_reconnect_voltage': 12.4,
        'under_voltage_recover_voltage': 12.0,
        'under_voltage_warning_voltage': 11.6,
        'low_voltage_disconnect_voltage': 10.80,
        'discharging_limit_voltage': 11.20,
        'equalize_duration': 0,
        'boost_duration': 10
    }

error:
Set all registers at once...
Traceback (most recent call last):
  File "_write_battery_params-LiTime.py", line 62, in <module>
    main()
  File "_write_battery_params-LiTime.py", line 44, in main
    battery_voltage_control_registers)
  File "/home/pi/.local/lib/python3.7/site-packages/epevermodbus/driver.py", line 346, in set_battery_voltage_control_registers_dict
    "set_battery_voltage_control_registers() got an unexpected keyword argument"
TypeError: set_battery_voltage_control_registers() got an unexpected keyword argument

I deleted examples 2 & 3 from the file and still got an error. 
Any ideas?
Thanks,
Jim

**Comment by jimlynnjulian** [comment]
Just read the --help list and noticed the durations are not included.
Thanks.
Closing.

**Comment by jimlynnjulian** [comment]
Could your script be modified?
I found this in Kasbert's 'registers.py.'

 Equalize duration
Setting("Equalize duration",
  0x906B, "Usually 60-120 minutes.",
  MIN, 1 ),
 Boost duration
Setting("Boost duration",
  0x906C, "Usually 60-120 minutes.",
  MIN, 1 ),"

https://github.com/kasbert/epsolar-tracer/blob/master/pyepsolartracer/registers.py

Thanks.
Jim J.

**Comment by jimlynnjulian** [comment]
Haven't been able too fiind another way to edit settings, so am reopening. Still looking, though.

**Comment by jimlynnjulian** [comment]
I managed to add code to read and write Equalization and Boost durations. Closing.
`
READ

from epevermodbus.driver import EpeverChargeController

controller = EpeverChargeController("/dev/ttyXRUSB0", 1)

bd = controller.get_boost_duration()
print ('boost duration',bd)
ed = controller.get_equalize_duration()
print ('equalization duration',ed)
ovdv = controller.get_over_voltage_disconnect_voltage()
print ('over_voltage_disconnect_voltage',ovdv)
ecv = controller.get_equalize_charging_voltage()
print ('equalize_charging_voltage',ecv)


WRITE

### Does not edit durations.
from minimalmodbus import SlaveReportedException
from epevermodbus.driver import EpeverChargeController

def main():
    portname = "/dev/ttyUSB0"
    slaveaddress = 1
    controller = EpeverChargeController(portname, slaveaddress)
    try:
        controller.set_battery_voltage_control_registers(
            boost_duration=130)
    except SlaveReportedException as err:
        print("The device reported an error:", err)
    # Set Example 2: Set a single register
    print("Set a single register 1...")
    controller.set_battery_voltage_control_registers(
        over_voltage_disconnect_voltage=14.7)
    print("Set a single register 2...")
    controller.set_battery_voltage_control_registers(
        equalize_charging_voltage=0.0)
`
